be strict in prepare scripts: exit on error

diff --git a/packages/carbonapi/prepare b/packages/carbonapi/prepare
--- a/packages/carbonapi/prepare
+++ b/packages/carbonapi/prepare
@@ -1,9 +1,14 @@
 #!/usr/bin/env bash
 
+set -e
+
 PACKAGE="carbonapi"
 VERSION="6ea1863"
 FILE="carbonapi-${VERSION}.tar.gz"
 URL="https://github.com/dgryski/carbonapi.git"
+
+command -v git >/dev/null 2>&1 || { echo "Please install git before running the prepare script.  Aborting." >&2; exit 1; }
+command -v go >/dev/null 2>&1 || { echo "Please install golang before running the prepare script.  Aborting." >&2; exit 1; }
 
 if [ ! -s "${PACKAGE}/${FILE}" ]; then
   mkdir -p ${PACKAGE}
diff --git a/packages/go-carbon/prepare b/packages/go-carbon/prepare
--- a/packages/go-carbon/prepare
+++ b/packages/go-carbon/prepare
@@ -1,9 +1,13 @@
 #!/usr/bin/env bash
 
+set -e
+
 PACKAGE="go-carbon"
 VERSION="0.9.1"
 FILE="go-carbon-${VERSION}.tar.gz"
 URL="https://github.com/lomik/go-carbon.git"
+
+command -v git >/dev/null 2>&1 || { echo "Please install git before running the prepare script.  Aborting." >&2; exit 1; }
 
 if [ ! -s "${PACKAGE}/${FILE}" ]; then
   mkdir -p ${PACKAGE}
diff --git a/packages/statsrelay/prepare b/packages/statsrelay/prepare
--- a/packages/statsrelay/prepare
+++ b/packages/statsrelay/prepare
@@ -1,9 +1,13 @@
 #!/usr/bin/env bash
 
+set -e
+
 PACKAGE="statsrelay"
 VERSION="f0e8abed"
 FILE="statsrelay-${VERSION}.tar.gz"
 URL="https://github.com/uber/statsrelay.git"
+
+command -v git >/dev/null 2>&1 || { echo "Please install git before running the prepare script.  Aborting." >&2; exit 1; }
 
 if [ ! -s "${PACKAGE}/${FILE}" ]; then
   mkdir -p ${PACKAGE}
